name: default
log_type: none # localfile
random_seed: 42
activate_proxies: [] # ['fmp','msd','fred','gt','exa'] #,'wa', 'gkg', 'pm', 'kb'
max_exception_retry: 3 
max_interrupt_times: 5
max_query_retry: 5
max_llm_recall: 0
system_type: basic # 'basic'
agent_configs:
  vanilla:
    model_name: o4-mini-2025-04-16 # o4-mini-2025-04-16
    system_prompt_path: vanilla/system
    temperature: 0.1
    max_completion_tokens: 20000

